# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: cloud

frameworkVersion: "3"

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs12.x

# The `functions` block defines what code to deploy
functions:
  save:
    handler: handler.save
    events:
      - sqs:
        arn: arn:aws:sqs:eu-central-1:587877384053:CDproject.fifo
        batchSize: 10
        maximumBatchingWindow: 60
        functionResponseType: ReportBatchItemFailures
