service: log2

custom:
  config: ${file(config/${opt:stage, 'dev'}.yml)}

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sqs:ReceiveMessage"
        - "sqs:DeleteMessage"
      Resource: "arn:aws:sqs:eu-central-1:587877384053:CDproject.fifo"

  environment:
    ENV: ${self:custom.config.ENV}

functions:
  processOrder:
    handler: handler.save
    # Setup Lambda Trigger
    events:
      - sqs:
          arn: "arn:aws:sqs:eu-central-1:587877384053:CDproject.fifo"
          batchSize: 1
